[general]
import = [
	"~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[window]
title = "アラクリティー"
dynamic_title = false
startup_mode = "Maximized"
decorations = "None"
option_as_alt = "OnlyLeft"

[font]
size = 10.0

[font.normal]
family = "BerkeleyMono Nerd Font"

[env]
term = "xterm-256color"
DOTDIR="$HOME/.dotfile"
XDG_CONFIG_HOME="$DOTDIR"

[selection]
save_to_clipboard = true
