default_keybindings = false
audio_cache_size = 1024
statusbar_format = "%title - %artists"

[track_format]
left = "%title - %artists"
center = ""
right = "%saved %duration"

[theme]
background = "#1E1E2E"
primary = "#6C7086"
secondary = "#313244"
title = "#A6ADC8"
playing = "#94E2D5"
playing_selected = "#94E2D5"
playing_bg = "#1E1E2E"
highlight = "#A6ADC8"
highlight_bg = "#181825"
error = "#F38BA8"
error_bg = "#181825"
statusbar = "#A6ADC8"
statusbar_progress = "#94E2D5"
statusbar_bg = "#181825"
cmdline = "#94E2D5"
cmdline_bg = "#181825"

[keybindings]
# settings
"Ctrl+r" = "reload"
"i" = "insert"
"?" = "help"
# movements
"Ctrl+n" = "move down 5"
"Ctrl+p" = "move up 5"
"h" = "move left 1"
"j" = "move down 1"
"k" = "move up 1"
"l" = "move right 1"
"g" = "move top"
"Shift+g" = "move bottom"
"Ctrl+o" = "back"
# players
"=" = "volup 5"
"-" = "voldown 5"
"m" = "voldown 100"
"Enter" = "play"
"p" = "playpause"
"a" = "goto artist"
"Shift+a" = "goto album"
"Shift+l" = "next"
"Shift+h" = "previous"
"Ctrl+l" = "seek +10000"
"Ctrl+h" = "seek -10000"
"s" = "stop"
"Shift+s" = "shuffle"
"r" = "repeat"
# screens
"1" = "focus library"
"2" = "focus queue"
"3" = "search"
# selections
"o" = "open selected"
"Shift+o" = "open current"
"y" = "share selected"
"Shift+y" = "share current"
# disables
"Ctrl+c" = "noop"
